import { Controller, Post, Delete, Body } from '@nestjs/common';
import { SimulationService } from './simulation.service';
import { InjectDataDto, RunSimulationDto } from './dto/run-simulation.dto';
import { ApiTags, ApiOperation } from '@nestjs/swagger';

@ApiTags('Simulation')
@Controller('simulation')
export class SimulationController {
  constructor(private readonly simulationService: SimulationService) {}

  @Post('inject')
  @ApiOperation({ summary: 'Inject dummy data into database (MySQL & MongoDB)' })
  async injectData(@Body() dto: InjectDataDto) {
    return this.simulationService.injectData(dto);
  }

  @Post('run')
  @ApiOperation({ summary: 'Run load testing simulation (Fetch & Search)' })
  async runSimulation(@Body() dto: RunSimulationDto) {
    return this.simulationService.runSimulation(dto);
  }

  @Delete('cleanup')
  @ApiOperation({ summary: 'Clean up dummy data generated by simulation' })
  async cleanup() {
    return this.simulationService.cleanup();
  }
}
